app:
    cors_allow_origins: https://funkapparat.billedapparat.test
    db_filename: funkapparat
    frontend_url: "https://funkapparat.billedapparat.test"
    log_format: json
    log_level: debug
    version: dev
    redis_url: redis://billedapparat_redis:6379/0

sentry:
    dsn: ""
    environment: development
    replay_error_sample_rate: 0.1
    replay_session_sample_rate: 0.1
    trace_sample_rate: 0.1
