#!/usr/bin/env bash
#MISE description="Start infrastructure services"

docker compose up -d --force-recreate --remove-orphans

echo ""
echo "🚀 --- INFRASTRUCTURE DASHBOARD -----------"
echo "📊    OpenObserve:    https://observe.billedapparat.test (admin@example.com / password123)"
echo "📊    RedisInsight:   https://redis.billedapparat.test"
echo "📣    Funkapparat:    http://localhost:3110" 
echo "⏳    Tidsapparat:    http://localhost:3120"
echo "🪪    Dex OIDC:       https://dex.billedapparat.test"
echo "-------------------------------------------"
