#!/usr/bin/env bash
#MISE description="Start infrastructure services"

docker compose up -d --force-recreate --remove-orphans

echo ""
echo "🚀 --- INFRASTRUCTURE DASHBOARD ---"
echo "📊 OpenObserve:   http://localhost:3105 (admin@example.com / password123)"
echo "📊 RedisInsight:  http://localhost:3106"
echo "📣 Funkapparat:   http://localhost:3110" 
echo "⏱️ Tidsapparat    http://localhost:3120"
echo "----------------------------------"
